export const IS_VALIDATING_LOGIN = 'IS_VALIDATING_LOGIN';
export const VALIDATE_LOGIN_DATA = 'VALIDATE_LOGIN_DATA';
export const FAILED_TO_VALIDATE_LOGIN_DATA  = 'FAILED_TO_VALIDATE_LOGIN_DATA ';
export const CLEAR_LOGIN_DATA = 'CLEAR_LOGIN_DATA';

export const IS_LOADING_EMPLOYEE_DATA = 'IS_LOADING_EMPLOYEE_DATA';
export const GET_EMPLOYEE_DATA = 'GET_EMPLOYEE_DATA';
export const FAILED_TO_GET_EMPLOYEE_DATA = 'FAILED_TO_GET_EMPLOYEE_DATA';
export const CLEAR_GET_EMPLOYEE_DATA = 'CLEAR_GET_EMPLOYEE_DATA';